/**
 * Rake CMS — Hooks System
 *
 * WordPress-compatible action and filter hooks.
 * Enables extensibility via plugins and themes.
 *
 * Actions: doAction / addAction — trigger/respond to events
 * Filters: applyFilters / addFilter — modify data
 *
 * Usage:
 *   import { addAction, doAction, addFilter, applyFilters } from "@/lib/hooks";
 *
 *   // Hook into post save
 *   addAction("save_post", async (postId) => {
 *     await syncToExternalService(postId);
 *   });
 *
 *   // Modify post content
 *   addFilter("the_content", (content) => {
 *     return content + "\n\n<!-- Generated by Rake CMS -->";
 *   });
 */

export {
  addAction,
  removeAction,
  removeAllActions,
  doAction,
  hasAction,
  didAction,
  resetActions,
} from "./actions";

export {
  addFilter,
  removeFilter,
  removeAllFilters,
  applyFilters,
  hasFilter,
  didFilter,
  resetFilters,
} from "./filters";
