// Auto-generated from WordPress theme — Rake CMS Migration
// Generated by import-theme command. Replace with actual theme content.

export default function Footer() {
  return (
    <footer className="site-footer border-t py-8">
      <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
        <p>
          Powered by <strong>Rake CMS</strong> &copy; {new Date().getFullYear()}
        </p>
      </div>
    </footer>
  );
}
