// Auto-generated from WordPress theme — Rake CMS Migration
// Generated by import-theme command. Replace with actual theme content.

import Link from "next/link";

export default function Header() {
  return (
    <header className="site-header border-b">
      <div className="container mx-auto px-4">
        <nav className="flex items-center justify-between py-4">
          <Link href="/" className="text-2xl font-bold">
            Rake CMS
          </Link>
          <div className="flex gap-6">
            <Link href="/" className="text-sm text-muted-foreground hover:text-foreground">
              Home
            </Link>
            <Link href="/blog" className="text-sm text-muted-foreground hover:text-foreground">
              Blog
            </Link>
            <Link href="/admin" className="text-sm text-muted-foreground hover:text-foreground">
              Admin
            </Link>
          </div>
        </nav>
      </div>
    </header>
  );
}
